"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .agentdto import AgentDTO, AgentDTOTypedDict
from flux0_client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class AgentsDTOTypedDict(TypedDict):
    data: List[AgentDTOTypedDict]


class AgentsDTO(BaseModel):
    data: List[AgentDTO]
