"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from flux0_client.types import BaseModel
from flux0_client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import Any, Literal
from typing_extensions import Annotated, TypedDict


class ContentPartDTOTypedDict(TypedDict):
    content: Any
    r"""Any valid JSON"""
    type: Literal["content"]


class ContentPartDTO(BaseModel):
    content: Any
    r"""Any valid JSON"""

    TYPE: Annotated[
        Annotated[Literal["content"], AfterValidator(validate_const("content"))],
        pydantic.Field(alias="type"),
    ] = "content"
