"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventcreationparamsdto import (
    EventCreationParamsDTO,
    EventCreationParamsDTOTypedDict,
)
from flux0_client.types import BaseModel
from flux0_client.utils import FieldMetadata, PathParamMetadata, RequestMetadata
from typing_extensions import Annotated, TypedDict


class CreateSessionEventRequestTypedDict(TypedDict):
    session_id: str
    r"""Unique identifier of the session"""
    event_creation_params_dto: EventCreationParamsDTOTypedDict


class CreateSessionEventRequest(BaseModel):
    session_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Unique identifier of the session"""

    event_creation_params_dto: Annotated[
        EventCreationParamsDTO,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
