"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class EventSourceDTO(str, Enum):
    r"""Source of the event within a session.

    Identifies who or what generated the event.
    """

    USER = "user"
    AI_AGENT = "ai_agent"
    SYSTEM = "system"
