"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .eventdto import EventDTO, EventDTOTypedDict
from flux0_client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class EventsDTOTypedDict(TypedDict):
    data: List[EventDTOTypedDict]


class EventsDTO(BaseModel):
    data: List[EventDTO]
