"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from flux0_client.types import BaseModel
from typing import Any
from typing_extensions import TypedDict


class Op(str, Enum):
    r"""The operation to perform"""

    ADD = "add"
    REPLACE = "replace"


class JSONPatchOperationDTOTypedDict(TypedDict):
    op: Op
    r"""The operation to perform"""
    path: str
    r"""The path to the target"""
    value: Any
    r"""Any valid JSON"""


class JSONPatchOperationDTO(BaseModel):
    op: Op
    r"""The operation to perform"""

    path: str
    r"""The path to the target"""

    value: Any
    r"""Any valid JSON"""
