"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sessiondto import SessionDTO, SessionDTOTypedDict
from flux0_client.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class SessionsDTOTypedDict(TypedDict):
    data: List[SessionDTOTypedDict]


class SessionsDTO(BaseModel):
    data: List[SessionDTO]
