"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .controloptions import ControlOptions, ControlOptionsTypedDict
from flux0_client.types import BaseModel
from typing import Any, Dict
from typing_extensions import TypedDict


class ToolResultDTOTypedDict(TypedDict):
    data: Any
    r"""Any valid JSON"""
    metadata: Dict[str, Any]
    control: ControlOptionsTypedDict


class ToolResultDTO(BaseModel):
    data: Any
    r"""Any valid JSON"""

    metadata: Dict[str, Any]

    control: ControlOptions
