"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolresultdto import ToolResultDTO, ToolResultDTOTypedDict
from flux0_client.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Any, Dict
from typing_extensions import NotRequired, TypedDict


class ToolCallDTOTypedDict(TypedDict):
    tool_call_id: str
    tool_name: str
    args: Dict[str, Any]
    result: NotRequired[Nullable[ToolResultDTOTypedDict]]
    error: NotRequired[Nullable[str]]


class ToolCallDTO(BaseModel):
    tool_call_id: str

    tool_name: str

    args: Dict[str, Any]

    result: OptionalNullable[ToolResultDTO] = UNSET

    error: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = ["result", "error"]
        nullable_fields = ["result", "error"]
        null_default_fields = []

        serialized = handler(self)

        m = {}

        for n, f in self.model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            serialized.pop(k, None)

            optional_nullable = k in optional_fields and k in nullable_fields
            is_set = (
                self.__pydantic_fields_set__.intersection({n})
                or k in null_default_fields
            )  # pylint: disable=no-member

            if val is not None and val != UNSET_SENTINEL:
                m[k] = val
            elif val != UNSET_SENTINEL and (
                not k in optional_fields or (optional_nullable and is_set)
            ):
                m[k] = val

        return m
