"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolcalldto import ToolCallDTO, ToolCallDTOTypedDict
from flux0_client.types import BaseModel
from flux0_client.utils import validate_const
import pydantic
from pydantic.functional_validators import AfterValidator
from typing import List, Literal
from typing_extensions import Annotated, TypedDict


class ToolEventDataDTOTypedDict(TypedDict):
    tool_calls: List[ToolCallDTOTypedDict]
    type: Literal["tool_call_result"]


class ToolEventDataDTO(BaseModel):
    tool_calls: List[ToolCallDTO]

    TYPE: Annotated[
        Annotated[
            Literal["tool_call_result"],
            AfterValidator(validate_const("tool_call_result")),
        ],
        pydantic.Field(alias="type"),
    ] = "tool_call_result"
