workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    FastAPI:
        inputs:
            - location: https://raw.githubusercontent.com/flux0-ai/flux0-api-spec/refs/heads/main/openapi.json
        registry:
            location: registry.speakeasyapi.dev/flux0/flux0-python/fast-api
targets:
    flux0:
        target: python
        source: FastAPI
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/flux0/flux0-python/fast-api-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
