"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .jsonpatchoperationdto import JSONPatchOperationDTO, JSONPatchOperationDTOTypedDict
from openapi.types import BaseModel
from typing import Any, Dict, List, Optional
from typing_extensions import NotRequired, TypedDict


class ChunkEventDTOTypedDict(TypedDict):
    event_id: str
    r"""Unique identifier for the event"""
    correlation_id: str
    r"""Identifier linking related events together"""
    seq: int
    r"""Sequential position of the chunk"""
    patches: List[JSONPatchOperationDTOTypedDict]
    metadata: Dict[str, Any]
    timestamp: NotRequired[float]


class ChunkEventDTO(BaseModel):
    event_id: str
    r"""Unique identifier for the event"""

    correlation_id: str
    r"""Identifier linking related events together"""

    seq: int
    r"""Sequential position of the chunk"""

    patches: List[JSONPatchOperationDTO]

    metadata: Dict[str, Any]

    timestamp: Optional[float] = None
