"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from openapi.types import BaseModel
from typing_extensions import TypedDict


class Mode(str, Enum):
    AUTO = "auto"
    MANUAL = "manual"


class ControlOptionsTypedDict(TypedDict):
    mode: Mode


class ControlOptions(BaseModel):
    mode: Mode
