"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .sessioncreationparamsdto import (
    SessionCreationParamsDTO,
    SessionCreationParamsDTOTypedDict,
)
from openapi.types import BaseModel
from openapi.utils import FieldMetadata, QueryParamMetadata, RequestMetadata
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateSessionRequestTypedDict(TypedDict):
    session_creation_params_dto: SessionCreationParamsDTOTypedDict
    allow_greeting: NotRequired[bool]
    r"""Indicates if the agent is permitted to send an initial greeting"""


class CreateSessionRequest(BaseModel):
    session_creation_params_dto: Annotated[
        SessionCreationParamsDTO,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]

    allow_greeting: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = False
    r"""Indicates if the agent is permitted to send an initial greeting"""
