"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .chunkeventstream import ChunkEventStream, ChunkEventStreamTypedDict
from .emittedeventstream import EmittedEventStream, EmittedEventStreamTypedDict
from openapi.utils import get_discriminator
from pydantic import Discriminator, Tag
from typing import Union
from typing_extensions import Annotated, TypeAliasType


SessionStreamTypedDict = TypeAliasType(
    "SessionStreamTypedDict",
    Union[ChunkEventStreamTypedDict, EmittedEventStreamTypedDict],
)


SessionStream = Annotated[
    Union[
        Annotated[ChunkEventStream, Tag("chunk")],
        Annotated[EmittedEventStream, Tag("status")],
    ],
    Discriminator(lambda m: get_discriminator(m, "event", "event")),
]
